#%RAML 0.8
title: Steroids Data
mediaType: application/json
baseUri: https://rest-api.appgyver.com/v1/

traits:
  - securedBySteroidsApiKey:
      headers:
        steroidsApiKey:
          type: string
          example: exampleapikey
          default: 7a9e6487e2d602e218fd08f3a1b546e9bcca16a658e0ba0b03c3d33d25b47741
        steroidsAppId:
          type: integer
          example: 1234
          default: 30552

schemas:
  - Users: '{"$schema":"http://json-schema.org/schema","title":"User collection","type":"object","properties":{"objects":{"type":"array","items":{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical User representation","properties":{"first_name":{"type":"string"},"last_name":{"type":"string"},"email":{"type":"string"},"avatar":{"type":"string"}},"required":[]}}}}'
  - User: '{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical User representation","properties":{"object":{"type":"object","properties":{"first_name":{"type":"string"},"last_name":{"type":"string"},"email":{"type":"string"},"avatar":{"type":"string"}},"required":[]}}}'
  - Posts: '{"$schema":"http://json-schema.org/schema","title":"Post collection","type":"object","properties":{"objects":{"type":"array","items":{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical Post representation","properties":{"content":{"type":"string"},"date_created":{"type":"string"},"date_modified":{"type":"string"},"id":{"type":"string"},"user":{"type":"string"},"likes":{"type":"string"},"likes_count":{"type":"integer"}},"required":[]}}}}'
  - Post: '{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical Post representation","properties":{"object":{"type":"object","properties":{"content":{"type":"string"},"date_created":{"type":"string"},"date_modified":{"type":"string"},"id":{"type":"string"},"user":{"type":"string"},"likes":{"type":"string"},"likes_count":{"type":"integer"}},"required":[]}}}'

resourceTypes:
  - dolan_db_collection:
      usage: This resourceType should be used for any collection of items
      is: [ securedBySteroidsApiKey ]
      get:
        description: |
          {
            "action": "collection"
          }
        responses:
          200:
            description: |
              {
                "rootKey": "objects"
              }
            body:
              application/json:
                schema: <<resourcePathName>> # e.g cars
      post:
        description: |
          {
            "action": "create",
            "rootKey": "object"
          }
        body:
          application/json:
            schema: <<resourcePathName | !singularize>>
        responses:
          200:
            description: |
              {
                "rootKey": "object"
              }
            body:
              application/json:
                schema: <<resourcePathName | !singularize>> # e.g. car

  - dolan_db_member:
      usage: This resourceType should be used for any built.io item
      is: [ securedBySteroidsApiKey ]
      get:
        description: |
          {
            "action": "find"
          }
        responses:
          200:
            description: |
              {
                "rootKey": "object"
              }
            body:
              application/json:
                schema: <<resourcePathName>> # e.g. car
      put:
        description: |
          {
            "action": "update",
            "rootKey": "object"
          }
        body:
          application/json:
            schema: <<resourcePathName | !singularize>>
        responses:
          200:
            description: |
              {
                "rootKey": "object"
              }
            body:
              application/json:
                schema: <<resourcePathName>>
      delete:
        description: |
          {
            "action": "destroy"
          }
        responses:
          200:
      


/User:
  description: |
    {
      "resourceName": "User",
      "identifierKey": "id"
    }
  type: dolan_db_collection
  /{id}:
    type: dolan_db_member

/Post:
  description: |
    {
      "resourceName": "Post",
      "identifierKey": "id"
    }
  type: dolan_db_collection
  /{id}:
    type: dolan_db_member


